# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CloudUploadStateStream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43loudUploadStateStream.proto\"a\n\x16\x43loudUploadStateStream\x12\x17\n\x0fuploadingStatus\x18\x01 \x01(\x08\x12\x15\n\rprogressBytes\x18\x02 \x01(\x05\x12\x17\n\x0fprogressPercent\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CloudUploadStateStream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOUDUPLOADSTATESTREAM._serialized_start=32
  _CLOUDUPLOADSTATESTREAM._serialized_end=129
# @@protoc_insertion_point(module_scope)
