# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DownloadResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44ownloadResponse.proto\"]\n\x10\x44ownloadResponse\x12\x19\n\x11\x64ownloadingStatus\x18\x01 \x01(\x08\x12\x15\n\rprogressBytes\x18\x02 \x01(\x05\x12\x17\n\x0fprogressPercent\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DownloadResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOWNLOADRESPONSE._serialized_start=26
  _DOWNLOADRESPONSE._serialized_end=119
# @@protoc_insertion_point(module_scope)
