# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: box_upload_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import box_common_api_pb2 as box__common__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ox_upload_api.proto\x12\x0e\x62ox_upload_api\x1a\x14\x62ox_common_api.proto\"d\n\x13\x44ownloadStateStream\x12,\n\x05state\x18\x01 \x01(\x0e\x32\x1d.box_upload_api.DownloadState\x12\x10\n\x08progress\x18\x02 \x01(\x04\x12\r\n\x05total\x18\x03 \x01(\x04\"{\n\x17\x44ownloadAllowanceStream\x12\x34\n\tallowance\x18\x01 \x01(\x0e\x32!.box_upload_api.DownloadAllowance\x12*\n\x04mode\x18\x02 \x01(\x0e\x32\x1c.box_upload_api.DownloadMode\"|\n\x18\x44ownloadAllowanceRequest\x12\x34\n\tallowance\x18\x01 \x01(\x0e\x32!.box_upload_api.DownloadAllowance\x12*\n\x04mode\x18\x02 \x01(\x0e\x32\x1c.box_upload_api.DownloadMode\"D\n\x10\x44ownloadResponse\x12\x30\n\x08response\x18\x01 \x01(\x0e\x32\x1e.box_common_api.ResponseStatus\"e\n\x16\x43loudUploadStateStream\x12*\n\x05state\x18\x01 \x01(\x0e\x32\x1b.box_upload_api.UploadState\x12\x10\n\x08progress\x18\x02 \x01(\x04\x12\r\n\x05total\x18\x03 \x01(\x04\"U\n\x1a\x43loudUploadAllowanceStream\x12\x37\n\tallowance\x18\x01 \x01(\x0e\x32$.box_upload_api.CloudUploadAllowance*B\n\rDownloadState\x12\x0f\n\x0bNOT_MOUNTED\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x08\n\x04\x42USY\x10\x02\x12\x0c\n\x08\x44L_ERROR\x10\x07*e\n\x0bUploadState\x12\x0e\n\nUP_UNKNOWN\x10\x00\x12\r\n\tNO_UPLOAD\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x12\x0c\n\x08\x46INISHED\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\x0c\n\x08UP_ERROR\x10\x07*E\n\x11\x44ownloadAllowance\x12\x0e\n\nDL_UNKNOWN\x10\x00\x12\x0e\n\nDL_ALLOWED\x10\x01\x12\x10\n\x0c\x44L_FORBIDDEN\x10\x02*5\n\x0c\x44ownloadMode\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\x08\n\x04PORT\x10\x01\x12\t\n\x05RADIO\x10\x02*K\n\x14\x43loudUploadAllowance\x12\x0f\n\x0b\x43UA_UNKNOWN\x10\x00\x12\x0f\n\x0b\x43UA_ALLOWED\x10\x01\x12\x11\n\rCUA_FORBIDDEN\x10\x02\x42\x1d\n\x19\x61pp.diab.box.apiv2.uploadP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'box_upload_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031app.diab.box.apiv2.uploadP\001'
  _DOWNLOADSTATE._serialized_start=675
  _DOWNLOADSTATE._serialized_end=741
  _UPLOADSTATE._serialized_start=743
  _UPLOADSTATE._serialized_end=844
  _DOWNLOADALLOWANCE._serialized_start=846
  _DOWNLOADALLOWANCE._serialized_end=915
  _DOWNLOADMODE._serialized_start=917
  _DOWNLOADMODE._serialized_end=970
  _CLOUDUPLOADALLOWANCE._serialized_start=972
  _CLOUDUPLOADALLOWANCE._serialized_end=1047
  _DOWNLOADSTATESTREAM._serialized_start=62
  _DOWNLOADSTATESTREAM._serialized_end=162
  _DOWNLOADALLOWANCESTREAM._serialized_start=164
  _DOWNLOADALLOWANCESTREAM._serialized_end=287
  _DOWNLOADALLOWANCEREQUEST._serialized_start=289
  _DOWNLOADALLOWANCEREQUEST._serialized_end=413
  _DOWNLOADRESPONSE._serialized_start=415
  _DOWNLOADRESPONSE._serialized_end=483
  _CLOUDUPLOADSTATESTREAM._serialized_start=485
  _CLOUDUPLOADSTATESTREAM._serialized_end=586
  _CLOUDUPLOADALLOWANCESTREAM._serialized_start=588
  _CLOUDUPLOADALLOWANCESTREAM._serialized_end=673
# @@protoc_insertion_point(module_scope)
