# Configuration for device and storage settings
device:
  inputDeviceName: "SD_CARD"
  inputDeviceMountPoint: "/media/dbox/"
# Configuration for Azure storage
azureStorage:
  containerName: "agrodronedata"
  storageAccountName: "dbox4storage"
  azureConnectionFileNameYAML: "azureConnection.yaml"
  azureConnectionFileNameJSON: "azureConnectionString.json"
  azurePreFolder: "DBOXNAME"

# Configuration for drone
drone:
  vendorID: "2ca3"

#DBOX index
dbox:
  index: 1

# Paths for folders
paths:
  imageFolderPath: "DCIM/" # Folder for where the photos are located inside the SD_CARD of the drone. for example /DCIM/photos.
  outputFolderPath: "/home/dbox/FileUpload/images/"

# Configuration for data processing
processing:
  deleteKeyWord: "DELETE_ME"
  timeInterval: 1  # in seconds
  uploadChunkSize: 1024  # in kilobytes
  downloadChunkSize: 2048  # in kilobytes

# MQTT configuration
mqtt:
  broker: "localhost"
  port: 1883
  topicDwnStr: "DBOX/DWNSTR"
  topicUplStr: "DBOX/UPLSTR"
  topicDwnRes: "DBOX/DWNRES"
  topicUplReq: "DBOX/UPLREQ"
  topicDwnReq: "DBOX/DWNREQ"
  qos: 0
  keepAlive: 60
  clientId: "DBOX"
  username: ""
  password: ""
  cleanSession: true
  connectionTimeout: 30
  lastWillTopic: "DBOX/STR"
  lastWillMessage: "DBOX file upload is offline"
  lastWillQos: 0
  lastWillRetain: false